apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: spingotest
  namespace: default
spec:
  scaledownPeriod: 10
  # cluster must keep some replica warm for CPU-heavy work
  replicas:
    min: 0
    max: 20
  hosts:
    - jc-wasm.digitalinnovation.be
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spingotest
    service: spingotest
    port: 80
  # prefer requestRate scaled to sustainable pod RPS (adjust from load tests)
  scalingMetric:
    requestRate:
      targetValue: 4
      granularity: 5s
  # keep pending requests relaxed for one/few intense/multi-second requests
  targetPendingRequests: 4
