#:schema https://schemas.spinframework.dev/spin/manifest-v2/latest.json

spin_manifest_version = 2

[application]
name = "spingotest"
version = "0.1.0"
authors = ["David Maat <r1036789@student.thomasmore.be>"]
description = ""

[[trigger.http]]
route = "/..."
component = "spingotest"

[component.spingotest]
source = "main.wasm"
allowed_outbound_hosts = ["https://api.open-meteo.com", "postgres://*.aws.neon.tech"]
[component.spingotest.build]
command = "tinygo build -target=wasip1 -buildmode=c-shared -no-debug -o main.wasm ."
watch = ["**/*.go", "go.mod"]
